{"uuid":"68cab77c-de3b-4d19-9283-e4050efd8ad4","historyId":"1ee6c483eacbcef8ac8632ec91e1af30","fullName":"org.example.crud.Integration_scenarios.TC_integration.testCreateBooking","labels":[{"name":"package","value":"org.example.crud.Integration_scenarios.TC_integration"},{"name":"testClass","value":"org.example.crud.Integration_scenarios.TC_integration"},{"name":"testMethod","value":"testCreateBooking"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"RESTfulbookerAPIAutomation"},{"name":"subSuite","value":"org.example.crud.Integration_scenarios.TC_integration"},{"name":"host","value":"DESKTOP-D42HOBV"},{"name":"thread","value":"17620@DESKTOP-D42HOBV.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testCreateBooking","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.ExceptionInInitializerError","trace":"java.lang.ExceptionInInitializerError\r\n\tat org.example.base.BaseTest.setConfig(BaseTest.java:40)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\r\n\tat org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.lang.RuntimeException: com.codoid.products.exception.FilloException: No records found\r\n\tat org.example.endpoints.APIConstants.<clinit>(APIConstants.java:16)\r\n\t... 30 more\r\nCaused by: com.codoid.products.exception.FilloException: No records found\r\n\tat com.codoid.products.fillo.Recordset.<init>(Recordset.java:40)\r\n\tat com.codoid.products.fillo.Connection.executeQuery(Connection.java:69)\r\n\tat org.example.utils.FilloUtil.fetchDataFromXLSX(FilloUtil.java:17)\r\n\tat org.example.endpoints.APIConstants.<clinit>(APIConstants.java:14)\r\n\t... 30 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1719218012527,"stop":1719218012528}